# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sjuO_iwcywWg19nb1bQUI9pAY3akEwzx
"""

def MapearVariables(df):
  Variables=df.columns.tolist()
  Lista_TipoDato=[]
  Lista_CantUnicos=[]
  Lista_VectorUnicos=[]
  Lista_CantNulos=[]
  for i in range(len(Variables)):
    Lista_TipoDato.append(df[Variables[i]].dtype)
    Lista_CantUnicos.append(df[Variables[i]].nunique())
    Lista_VectorUnicos.append(df[Variables[i]].unique().tolist())
    Lista_CantNulos.append(df[Variables[i]].isnull().sum())
  Resumen=pd.DataFrame({"Variable":Variables,"TipoDato":Lista_TipoDato,
                      "CatUnicos":Lista_CantUnicos,"VectorUnicos":Lista_VectorUnicos,
                      "Nulos":Lista_CantNulos})
  Resumen["PorcentajeNulos"]=(Resumen["Nulos"]/len(df))*100
  return Resumen

